"""Brief synthesis + Pushover delivery + closed-form-brief resolution.

Briefs are the PM's user-facing output. They land as `pm:brief` comments and
push a notification with a deep-link to the thread. The body is generated by
Haiku from spec + recent PM episodes + the triggering event.

Closed-form briefs also emit a sibling `pm:brief-options` comment (JSON) so
that claude-view can render option buttons. Resolution is via apply_decision()
which is called by both the CLI (brief-resolve) and the tick-loop directive
consumer.

Directive file shape (written by claude-view, consumed by the tick loop):
    {
      "brief_id": "04af254c-...",
      "target_id": "my-target",
      "option_id": "B",
      "ts": "2026-05-02T07:55:00-07:00",
      "submitter": "claude-view"
    }

pm:brief-options comment JSON shape:
    {
      "brief_id": "<comment_id_of_pm:brief_comment>",
      "trigger": "advisory-screen-issue",
      "options": [
        {"id": "A", "label": "...", "action": {"kind": "merge_pr", "pr": 17}},
        {"id": "B", "label": "...", "action": {"kind": "force_dispatch_retry"}},
        {"id": "C", "label": "...", "action": {"kind": "pause_target"}}
      ]
    }
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from agents_core.llm import call_claude_cli
from agents_core.notify import send_notification, Priority as NotifyPriority

from . import episodic

logger = logging.getLogger(__name__)

_BRIEF_MODEL = "haiku"
_BRIEF_RETRIES = 1


def _brief_version_line() -> str:
    """One-line running-version provenance appended to every emitted brief.

    Sourced from the *running* module tree (not origin/main) so a stale deploy
    is immediately visible in the brief: 'lapis_pm @ <old-sha>' vs origin.
    """
    repo_root = Path(__file__).parent.parent
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo_root), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, timeout=5,
        )
        sha = proc.stdout.strip() if proc.returncode == 0 else "unknown"
    except Exception:
        sha = "unknown"
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ")
    return f"\n---\n*lapis_pm @ {sha}, brief.py:{_BRIEF_MODEL}, {ts}*"


DASHBOARD_BASE = "http://203.0.113.12:8400"   # Conductor dashboard
_DIFF_CAP = 30000

BRIEF_SYSTEM = """You are the Lapis PM agent producing a *brief* for Erah.

Output Markdown in this exact structure (no preamble, no closing):

## State
<2 sentences on where this thread stands right now>
## Recent activity
- <bullet 1, terse>
- <bullet 2, terse>
- <bullet 3, terse>
## Risk / spec deviation
<One sentence — or "none">
## Decision needed
<One sentence — or "none" if no decision is required>
## Options
- A: <option> — <risk/cost in <=12 words>
- B: <option> — <risk/cost in <=12 words>

Rules:
- Be terse. Erah is context-switching from another thread; he has 30 seconds.
- Skip "Options" entirely if Decision needed is "none".
- Grounding rule: Every claim in 'Risk / spec deviation' MUST cite either (a) a `screen_issues` entry by its severity+path, or (b) a specific line or symbol from the diff section. If neither is available, output `none` for that section.
- No-screen rule: If the user message states 'no inline screen ran for this PR', the 'Risk / spec deviation' section outputs `none` unless the diff section contains concrete evidence of a problem (held path, deleted test, scope creep beyond spec). Do not infer schema violations, missing dependencies, or convention breaks from a truncated diff.
- No-absence-from-truncation rule: You cannot conclude something is missing or absent from a truncated diff. If the diff section ends with `(diff truncated)`, do not make absence-claims (e.g. 'missing dependency X', 'no test for Y'); consult the spec_summary for declared dependencies/structure instead, and only claim absence when the spec affirmatively says X should exist and the diff section is complete.
- Reviewer-anchor rule: When the user message contains a 'Reviewer verdict:' block and that verdict reads 'verdict=clean', the 'Risk / spec deviation' section MUST output `none` UNLESS the diff section shows a held path under {Lapis,room,registry}.yaml or a deleted/skipped test. Do not infer truncation, missing implementation, or schema violations when Opus has already returned clean. The reviewer has the full diff; the composer does not.
- Never invent state — if you don't know something, omit it.
"""

# ---------------------------------------------------------------------------
# Closed-form trigger → options definitions
# ---------------------------------------------------------------------------

# The four supported action kinds.  Any other string is an error.
_ACTION_KINDS = {"merge_pr", "force_dispatch_retry", "pause_target", "unbind_target", "acknowledge_and_clear"}

# Closed-form trigger strings → option list templates.
# For merge_pr actions the actual pr number is injected at synthesize() time
# when pr_number is provided; otherwise the "pr" key is omitted (the action
# handler will derive it from the outstanding brief context).
_CLOSED_FORM_TRIGGERS: dict[str, list[dict]] = {
    "advisory-screen-issue": [
        {
            "id": "A",
            "label": "Merge anyway — advisory issues are minor",
            "action": {"kind": "merge_pr"},
        },
        {
            "id": "B",
            "label": "Brief back to fixer with the screen issues",
            "action": {"kind": "force_dispatch_retry"},
        },
        {
            "id": "C",
            "label": "Pause this target",
            "action": {"kind": "pause_target"},
        },
    ],
    "advisory-clean": [
        {
            "id": "A",
            "label": "Merge the PR",
            "action": {"kind": "merge_pr"},
        },
        {
            "id": "B",
            "label": "Acknowledge and clear brief",
            "action": {"kind": "acknowledge_and_clear"},
        },
    ],
    "lost-dispatch": [
        {
            "id": "A",
            "label": "Retry again",
            "action": {"kind": "force_dispatch_retry"},
        },
        {
            "id": "B",
            "label": "Amend spec and retry",
            "action": {"kind": "acknowledge_and_clear"},
        },
        {
            "id": "C",
            "label": "Unbind this target",
            "action": {"kind": "unbind_target"},
        },
    ],
    "orphan-pr-untraceable": [
        {
            "id": "A",
            "label": "Adopt this PR into the PM loop",
            "action": {"kind": "force_dispatch_retry"},
        },
        {
            "id": "B",
            "label": "Close this PR",
            "action": {"kind": "acknowledge_and_clear"},
        },
        {
            "id": "C",
            "label": "Ignore for now",
            "action": {"kind": "acknowledge_and_clear"},
        },
    ],
}

# Directive consumer path
_DIRECTIVES_BASE = Path("/srv/lapis/directives/brief-decisions")


@dataclass
class Brief:
    target_id: str
    body: str
    comment_id: str
    pushed: bool


def _format_episodes(scored: list[episodic.ScoredComment], limit_chars: int = 200) -> str:
    if not scored:
        return "(no recent PM episodes)"
    lines = []
    for s in scored:
        c = s.comment
        snippet = c.content.replace("\n", " ")
        if len(snippet) > limit_chars:
            snippet = snippet[:limit_chars] + "…"
        tags = ",".join(c.tags) if c.tags else "-"
        lines.append(f"- [{c.ts}] ({tags}) {snippet}")
    return "\n".join(lines)


def _synthesize_body(user: str) -> str | None:
    return call_claude_cli(
        prompt=user, system=BRIEF_SYSTEM,
        model=_BRIEF_MODEL, timeout=120, log=logger.warning,
    ) or None


def synthesize(
    target_id: str,
    trigger: str,
    query: str = "",
    diff_snippet: str | None = None,
    screen_issues: list[dict] | None = None,
    pr_number: int | None = None,
    *,
    notify: NotifyPriority | None = NotifyPriority.NORMAL,
    options_extra_tags: list[str] | None = None,
    reviewer_verdict_text: str | None = None,
) -> Brief:
    """Produce a brief, write it as a comment, optionally push to Pushover.

    diff_snippet: first ~3000 chars of the PR diff (from PRClassification.diff)
    screen_issues: structured issue list from the authority screen
    pr_number: PR number for merge_pr action in closed-form briefs
    notify: NotifyPriority.X → write comment AND call send_notification at that priority.
            None → write pm:brief comment but skip send_notification; Brief.pushed=False.

    When trigger is a closed-form trigger, also writes a sibling pm:brief-options
    comment so that claude-view can render resolution buttons.  The brief markdown
    body is never modified — Pushover and existing renderer are unaffected.
    """
    spec_summary = episodic.spec_summary(target_id, max_chars=4000)
    recent = episodic.recall(target_id, query or trigger, k=6)
    episodes_block = _format_episodes(recent)

    diff_block = ""
    if diff_snippet:
        snippet = diff_snippet[:_DIFF_CAP]
        if len(diff_snippet) > _DIFF_CAP:
            snippet += "\n…(diff truncated)"
        diff_block = f"\nPR diff:\n```diff\n{snippet}\n```\n"

    issues_block = ""
    if screen_issues:
        lines = [
            f"- [{i.get('severity','?')}] {i.get('path','')} — {i.get('note','')}"
            for i in screen_issues[:8]
        ]
        issues_block = "\nScreen issues:\n" + "\n".join(lines) + "\n"

    inline_screen = (
        "ran"
        if screen_issues
        else "did not run — Opus reviewer is the gate for this advisory-tier PR"
    )
    trigger_block = f"Trigger: {trigger}\nInline screen: {inline_screen}\n"

    verdict_block = ""
    if reviewer_verdict_text:
        verdict_block = f"Reviewer verdict:\n{reviewer_verdict_text}\n"

    user = (
        f"Thread: {target_id}\n"
        f"{trigger_block}\n"
        f"Spec:\n{spec_summary}\n\n"
        f"Recent PM episodes (most relevant first):\n{episodes_block}\n"
        f"{verdict_block}"
        f"{diff_block}"
        f"{issues_block}"
    )

    body = None
    for _ in range(_BRIEF_RETRIES + 1):
        body = _synthesize_body(user)
        if body:
            break
    if not body:
        body = (
            "## State\nBrief synthesis failed — composer call returned empty.\n"
            "## Recent activity\n"
            f"{episodes_block}\n"
            "## Decision needed\nReview thread directly.\n"
        )

    body = body + _brief_version_line()

    comment = episodic.write_brief(target_id, body)

    # Emit sibling pm:brief-options comment for closed-form triggers.
    # The brief body is unchanged; this is purely additive.
    if trigger in _CLOSED_FORM_TRIGGERS:
        _write_options_sibling(target_id, comment.id, trigger, pr_number,
                               extra_tags=options_extra_tags)

    deep_link = f"{DASHBOARD_BASE}/thread/{target_id}"
    pushed = False
    if notify is not None:
        pushed = send_notification(
            message=body,
            title=f"Lapis PM: {target_id}",
            priority=notify,
            url=deep_link,
            url_title="Open thread",
        )

    return Brief(target_id=target_id, body=body, comment_id=comment.id, pushed=pushed)


def _write_options_sibling(
    target_id: str,
    brief_id: str,
    trigger: str,
    pr_number: int | None,
    extra_tags: list[str] | None = None,
) -> None:
    """Write the pm:brief-options sibling comment for a closed-form trigger."""
    import copy
    option_templates = _CLOSED_FORM_TRIGGERS.get(trigger)
    if not option_templates:
        return
    options = copy.deepcopy(option_templates)
    # Inject pr_number into merge_pr actions when known.
    if pr_number is not None:
        for opt in options:
            if opt.get("action", {}).get("kind") == "merge_pr":
                opt["action"]["pr"] = pr_number
    payload = {
        "brief_id": brief_id,
        "trigger": trigger,
        "options": options,
    }
    episodic.write_brief_options(target_id, json.dumps(payload, ensure_ascii=False),
                                 extra_tags=extra_tags)


# ---------------------------------------------------------------------------
# read_options — find the sibling pm:brief-options comment for a brief_id
# ---------------------------------------------------------------------------

def read_options(target_id: str, brief_id: str) -> dict | None:
    """Return parsed pm:brief-options JSON for brief_id, or None on any error.

    Never raises — callers can assume safe fallback to None.
    """
    try:
        for c in episodic.all_comments(target_id):
            if episodic.TAG_BRIEF_OPTIONS not in c.tags:
                continue
            try:
                data = json.loads(c.content)
            except (json.JSONDecodeError, ValueError):
                continue
            if data.get("brief_id") == brief_id:
                # Basic shape validation
                if not isinstance(data.get("options"), list):
                    return None
                return data
    except Exception:
        pass
    return None


# ---------------------------------------------------------------------------
# apply_decision — the single resolution path (CLI + directive consumer)
# ---------------------------------------------------------------------------

def apply_decision(target_id: str, brief_id: str, option_id: str) -> dict:
    """Resolve a closed-form brief by executing the chosen option.

    Returns:
        {ok: bool, action_kind: str, detail: str}
        or {ok: False, error: str}

    Idempotency: if decision/brief-resolved/<brief_id> audit key already exists,
    returns {ok: True, action_kind: "noop_already_applied", detail: ...}.
    If brief_id doesn't match the current outstanding brief, returns
    {ok: False, error: "stale_brief"}.
    """
    from . import pm_core as _pm

    # Idempotency probe — audit key already set means this was applied before.
    audit_key = f"decision/brief-resolved/{brief_id}"
    existing_audit = _pm._mem().get(audit_key)
    if existing_audit:
        try:
            audit_data = json.loads(existing_audit["content"])
        except (json.JSONDecodeError, KeyError):
            audit_data = {}
        return {
            "ok": True,
            "action_kind": "noop_already_applied",
            "detail": f"already applied: {audit_data.get('action_kind', '?')} at {audit_data.get('ts', '?')}",
        }

    # Stale-brief check: the outstanding brief must match brief_id.
    current_outstanding = _pm.get_outstanding_brief(target_id)
    if current_outstanding != brief_id:
        return {
            "ok": False,
            "error": "stale_brief",
        }

    # Look up the options comment.
    opts = read_options(target_id, brief_id)
    if opts is None:
        return {
            "ok": False,
            "error": "options_not_found",
        }

    # Find the chosen option.
    chosen = next((o for o in opts.get("options", []) if o.get("id") == option_id), None)
    if chosen is None:
        return {
            "ok": False,
            "error": f"unknown_option_id:{option_id}",
        }

    action = chosen.get("action", {})
    kind = action.get("kind", "")

    # Execute the action.
    try:
        if kind == "merge_pr":
            pr_number = action.get("pr")
            result_detail = _act_merge_pr(target_id, pr_number)
        elif kind == "force_dispatch_retry":
            result_detail = _act_force_dispatch_retry(target_id, brief_id)
        elif kind == "pause_target":
            result_detail = _act_pause_target(target_id)
        elif kind == "unbind_target":
            result_detail = _act_unbind_target(target_id)
        elif kind == "acknowledge_and_clear":
            result_detail = _act_acknowledge_and_clear(target_id)
        else:
            return {"ok": False, "error": f"unknown_action_kind:{kind}"}
    except Exception as exc:
        return {"ok": False, "error": f"action_failed:{kind}:{exc}"}

    # Clear the outstanding brief.
    _pm.clear_outstanding_brief(target_id, reason="principal_decision")

    # Write audit key for idempotency + trajectory.
    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
    audit_record = {
        "target_id": target_id,
        "option_id": option_id,
        "action_kind": kind,
        "ts": ts,
        "result": result_detail,
    }
    _pm._mem().set(audit_key, json.dumps(audit_record, ensure_ascii=False),
                   tags=["lapis-pm", "brief-resolved"])

    episodic.write_observation(
        target_id,
        f"Brief {brief_id} resolved via option {option_id} ({kind}): {result_detail}",
        extra_tags=["pm:brief-resolved", f"pm:brief-id={brief_id}"],
    )

    return {"ok": True, "action_kind": kind, "detail": result_detail}


# ---------------------------------------------------------------------------
# Private action implementations
# ---------------------------------------------------------------------------

def _act_merge_pr(target_id: str, pr_number: int | None) -> str:
    """Merge the advisory PR cited by the brief."""
    from agents_core.targets import TargetStore
    try:
        from agents_core.forgejo import merge_pr as _merge_pr
    except ImportError as exc:
        raise RuntimeError(f"forgejo not available: {exc}") from exc

    store = TargetStore()
    target = store.get(target_id)
    repo = (target.pm_repo if target else None) or ""
    if not repo:
        raise ValueError("target has no pm_repo")
    if pr_number is None:
        raise ValueError("pr_number required for merge_pr action")
    if "/" in repo:
        owner, repo_name = repo.split("/", 1)
    else:
        repo_name, owner = repo, None
    _merge_pr(repo_name, pr_number, owner=owner)
    return f"merged PR #{pr_number} in {repo}"


def _act_force_dispatch_retry(target_id: str, brief_comment_id: str) -> str:
    """Force-dispatch fixer referencing the outstanding brief comment."""
    from . import pm_core as _pm
    intent = (
        f"Address outstanding brief comment {brief_comment_id}. "
        "Spec is source of truth."
    )
    task_id = _pm.force_dispatch(target_id, "fixer", intent)
    return f"force_dispatch fixer task_id={task_id}"


def _act_pause_target(target_id: str) -> str:
    """Set paused=true for the target."""
    from . import pm_core as _pm
    _pm.set_pause_state(target_id, "paused")
    from agents_core.targets import TargetStore
    store = TargetStore()
    target = store.get(target_id)
    if target is not None:
        target.set_paused(True, reason="brief option: pause_target")
        target.save()
    return "target paused"


def _act_unbind_target(target_id: str) -> str:
    """Remove pm_bound from the target (hard stop — no further ticks)."""
    from agents_core.targets import TargetStore
    from . import pm_core as _pm
    store = TargetStore()
    target = store.get(target_id)
    if target is not None:
        target.unbind_pm()
        target.save()
    _pm.clear_classified_prs(target_id)
    return "target unbound"


def _act_acknowledge_and_clear(target_id: str) -> str:
    """Informational brief — just clear the outstanding brief."""
    # clear_outstanding_brief is called by apply_decision after this returns.
    # Nothing else to do for acknowledge_and_clear.
    return "acknowledged and cleared"
