"""Brief synthesis + Pushover delivery.

Briefs are the PM's user-facing output. They land as `pm:brief` comments and
push a notification with a deep-link to the thread. The body is generated by
Haiku from spec + recent PM episodes + the triggering event.
"""

from __future__ import annotations

from dataclasses import dataclass

from agents_core.llm import call_claude_cli
from agents_core.notify import send_notification, Priority as NotifyPriority

from . import episodic


DASHBOARD_BASE = "http://203.0.113.12:8400"   # Conductor dashboard
BRIEF_SYSTEM = """You are the Lapis PM agent producing a *brief* for Erah.

Output Markdown in this exact structure (no preamble, no closing):

## State
<2 sentences on where this thread stands right now>
## Recent activity
- <bullet 1, terse>
- <bullet 2, terse>
- <bullet 3, terse>
## Risk / spec deviation
<One sentence flagging any spec violation, held path, or test gap — or "none">
## Decision needed
<One sentence — or "none" if no decision is required>
## Options
- A: <option> — <risk/cost in <=12 words>
- B: <option> — <risk/cost in <=12 words>

Rules:
- Be terse. Erah is context-switching from another thread; he has 30 seconds.
- Skip "Options" entirely if Decision needed is "none".
- Skip "Risk / spec deviation" section only if there is truly nothing to flag.
- If a diff is provided, read it carefully: call out missing tests for behavior
  changes, scope creep beyond the target spec, or any high-severity screen issues.
- Never invent state — if you don't know something, omit it.
"""


@dataclass
class Brief:
    target_id: str
    body: str
    comment_id: str
    pushed: bool


def _format_episodes(scored: list[episodic.ScoredComment], limit_chars: int = 200) -> str:
    if not scored:
        return "(no recent PM episodes)"
    lines = []
    for s in scored:
        c = s.comment
        snippet = c.content.replace("\n", " ")
        if len(snippet) > limit_chars:
            snippet = snippet[:limit_chars] + "…"
        tags = ",".join(c.tags) if c.tags else "-"
        lines.append(f"- [{c.ts}] ({tags}) {snippet}")
    return "\n".join(lines)


def synthesize(
    target_id: str,
    trigger: str,
    query: str = "",
    diff_snippet: str | None = None,
    screen_issues: list[dict] | None = None,
    *,
    notify: NotifyPriority | None = NotifyPriority.NORMAL,
) -> Brief:
    """Produce a brief, write it as a comment, optionally push to Pushover.

    diff_snippet: first ~3000 chars of the PR diff (from PRClassification.diff)
    screen_issues: structured issue list from the authority screen
    notify: NotifyPriority.X → write comment AND call send_notification at that priority.
            None → write pm:brief comment but skip send_notification; Brief.pushed=False.
    """
    spec_summary = episodic.spec_summary(target_id, max_chars=4000)
    recent = episodic.recall(target_id, query or trigger, k=6)
    episodes_block = _format_episodes(recent)

    diff_block = ""
    if diff_snippet:
        snippet = diff_snippet[:3000]
        if len(diff_snippet) > 3000:
            snippet += "\n…(diff truncated)"
        diff_block = f"\nPR diff:\n```diff\n{snippet}\n```\n"

    issues_block = ""
    if screen_issues:
        lines = [
            f"- [{i.get('severity','?')}] {i.get('path','')} — {i.get('note','')}"
            for i in screen_issues[:8]
        ]
        issues_block = "\nScreen issues:\n" + "\n".join(lines) + "\n"

    user = (
        f"Thread: {target_id}\n"
        f"Trigger: {trigger}\n\n"
        f"Spec:\n{spec_summary}\n\n"
        f"Recent PM episodes (most relevant first):\n{episodes_block}\n"
        f"{diff_block}"
        f"{issues_block}"
    )

    body = call_claude_cli(
        prompt=user, system=BRIEF_SYSTEM,
        model="haiku", timeout=120,
    )
    if not body:
        body = (
            "## State\nBrief synthesis failed — Haiku call returned empty.\n"
            "## Recent activity\n"
            f"{episodes_block}\n"
            "## Decision needed\nReview thread directly.\n"
        )

    comment = episodic.write_brief(target_id, body)

    deep_link = f"{DASHBOARD_BASE}/thread/{target_id}"
    pushed = False
    if notify is not None:
        pushed = send_notification(
            message=body,
            title=f"Lapis PM: {target_id}",
            priority=notify,
            url=deep_link,
            url_title="Open thread",
        )

    return Brief(target_id=target_id, body=body, comment_id=comment.id, pushed=pushed)
